### ISSUE TITLE
Security vulnerabilities of ubuntu base images

### ISSUE THREAD

**Issue by nolik** [adoptium/containers#162]
As part of [trivy container  vulnerability scanner ](https://github.com/aquasecurity/trivy) our team figured out the next HIGH vulnerabilities:

- https://ubuntu.com/security/notices/USN-5301-1
- https://ubuntu.com/security/notices/USN-5301-2

Need to investigate but the latest ubuntu base image should contain fixes for those packages.

**Comment by bjornmagnusson** [comment]
Our team also have discovered a couple of vulnerabilities, but using Docker scan with Snyk.
`Testing eclipse-temurin:11.0.14.1_1-jre...

✗ High severity vulnerability found in expat/libexpat1
  Description: Exposure of Resource to Wrong Sphere
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-EXPAT-2403778
  Introduced through: fontconfig@2.13.1-2ubuntu3, what-is-python/python-is-python3@3.8.2-4
  From: fontconfig@2.13.1-2ubuntu3 > fontconfig/libfontconfig1@2.13.1-2ubuntu3 > expat/libexpat1@2.2.9-1build1
  From: what-is-python/python-is-python3@3.8.2-4 > python3-defaults/python3@3.8.2-0ubuntu2 > python3.8@3.8.10-0ubuntu1~20.04.2 > python3.8/python3.8-minimal@3.8.10-0ubuntu1~20.04.2 > expat/libexpat1@2.2.9-1build1
  Fixed in: 2.2.9-1ubuntu0.2

✗ High severity vulnerability found in expat/libexpat1
  Description: Improper Encoding or Escaping of Output
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-EXPAT-2403934
  Introduced through: fontconfig@2.13.1-2ubuntu3, what-is-python/python-is-python3@3.8.2-4
  From: fontconfig@2.13.1-2ubuntu3 > fontconfig/libfontconfig1@2.13.1-2ubuntu3 > expat/libexpat1@2.2.9-1build1
  From: what-is-python/python-is-python3@3.8.2-4 > python3-defaults/python3@3.8.2-0ubuntu2 > python3.8@3.8.10-0ubuntu1~20.04.2 > python3.8/python3.8-minimal@3.8.10-0ubuntu1~20.04.2 > expat/libexpat1@2.2.9-1build1
  Fixed in: 2.2.9-1ubuntu0.2

✗ High severity vulnerability found in cyrus-sasl2/libsasl2-modules-db
  Description: CVE-2022-24407
  Info: https://snyk.io/vuln/SNYK-UBUNTU2004-CYRUSSASL2-2408941
  Introduced through: curl@7.68.0-1ubuntu2.7
  From: curl@7.68.0-1ubuntu2.7 > curl/libcurl4@7.68.0-1ubuntu2.7 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.8 > cyrus-sasl2/libsasl2-2@2.1.27+dfsg-2 > cyrus-sasl2/libsasl2-modules-db@2.1.27+dfsg-2
  From: curl@7.68.0-1ubuntu2.7 > curl/libcurl4@7.68.0-1ubuntu2.7 > openldap/libldap-2.4-2@2.4.49+dfsg-2ubuntu1.8 > cyrus-sasl2/libsasl2-2@2.1.27+dfsg-2
  Fixed in: 2.1.27+dfsg-2ubuntu0.1`

**Comment by karianna** [comment]
@gdams - Do we need to update these or does DockerHub do that (via the base ubuntu-latest?

**Comment by julillosamaral** [comment]
> @gdams - Do we need to update these or does DockerHub do that (via the base ubuntu-latest?

I don't know if it helps, but snyk recommends using: ubuntu impish-20220128, I think it's 21.10

**Comment by tianon** [comment]
I think there's probably two separate relevant things to cover here:

- the `ubuntu` image should definitely be updated; I think it's roughly "due" for one (which will of course rebuild all the downstream images and thus include any relevant updated packages); I'll poke some folks at Canonical and see what their plan is -- I would _guess_ their plan is probably to update within a week from now (at the outside)

- whether/when to update to _new_ versions of your base is up to you -- I'd recommend keeping in mind that it usually does cause some breakage for users, and the way we usually manage that in other repositories is to add aliases such that users have an easy/obvious escape hatch to downgrade again if they experience issues (see https://hub.docker.com/_/python or https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#supported-tags-and-respective-dockerfile-links :joy: for example); in most cases we try to limit to at most two versions of a given OS (and LTS where possible), given that there's added cognitive overhead for users ("which version/OS combination should I use??") _and_ build overhead in supporting more

cc @yosifkit

**Comment by jorhett** [comment]
Also https://ubuntu.com/security/notices/USN-5328-1 is even higher risk for most people. An updated image would be good.

**Comment by vcarluer** [comment]
Hello,

I've been redirected here to submit my security case.

Our GitHub container scan tool detected the eclipse-temurin:17-alpine image is vulnerable to the high CVE CVE-2022-0778: https://avd.aquasec.com/nvd/2022/cve-2022-0778/
This report happened 6 days ago after your release.
Our scan report: https://github.com/Cosmo-Tech/cosmotech-api/pull/217/checks?check_run_id=5601109545

Can you please confirm if this is related to your new version or not and if you have visibility on a fix?

Thanks, don't hesitate if I can bring any other information.

**Comment by karianna** [comment]
Discussion at PMC:

"We could check all of the supported Linux Vendors and see if they have public APIs that we can poll to see if a new point release has come out.  If so, then GH Action our way to victory."

**Comment by karianna** [comment]
Please see https://github.com/adoptium/containers/pull/183 for an update to our policy and what actually happens at DockerHub.
