### ISSUE TITLE
[Bug]: alpine jre does not seem to get updated

### ISSUE THREAD

**Issue by paoliniluis** [adoptium/containers#302]
### Please add the exact image (with tag) that you are using

11-jre-alpine

### Please add the version of Docker you are running

Latest

### What happened?

The last change in the alpine dockerfile was 6 days ago, but the last image pushed was more than 20 days ago, is there something going on with the process that the images don't get updated in Dockerhub?

**Comment by karianna** [comment]
DockerHub generates the final images.  What change are you not seeing?

**Comment by paoliniluis** [comment]
Hi @karianna, thanks for the quick reply. I saw that the last time that the 11-jre-alpine image was pushed was 24 days ago, 
![image](https://user-images.githubusercontent.com/1711649/199128291-8b5cf454-0310-4386-baec-8ab04a788e44.png)
while the last time that the Dockerfile changed was 6 days ago
![image](https://user-images.githubusercontent.com/1711649/199128363-39faf593-4ea3-45ac-ae51-2a07553a72fe.png)

If Dockerfile generates the final image, maybe a hook is broken? or Dockerhub pipelines got clogged and images are not being generated? There have been many CVE's reported in the 11-jre-alpine image during these days and I want to be sure that I pull the most secure image possible every time I pull those in my pipelines

**Comment by karianna** [comment]
@paoliniluis DockerHub actually provides the Alpine Base layer so to speak, so that should be kept up to date by them.  We add our Temurin builds on top of that.  We've just gone through a release cycle and I see the alpine images got updated ~7 days ago and submitted so I'd expect DockerHub to release the new images. It does seem a little odd they're not out yet.

Paging @tianon for a sense check here

**Comment by tianon** [comment]
This was updated via https://github.com/docker-library/official-images/pull/13516 :+1:
