### ISSUE TITLE
Support UBI 9 minimal container images

### ISSUE THREAD

**Issue by tellison** [adoptium/containers#308]
There is an open request for [UBI to be an official docker base image](https://github.com/docker-library/official-images/issues/9445).

This is of [interest](https://github.com/AdoptOpenJDK/openjdk-docker/issues/581) to our community and has come up in discussion as a logical successor to CentOS in due course. We'd like to run CentOS and UBI in parallel as we transition users.

To achieve progress on both these goals that we'll work with Docker and Red Hat on adding Eclipse Temurin UBI minimal to our dockerfile generator scripts in this repo, and test locally.

Assuming that goes well we'd plan on providing a file that is based upon redhat/ubi9-minimal across all supported platforms for the docker to use as [an official image](https://hub.docker.com/_/eclipse-temurin).

**Comment by smlambert** [comment]
Adding this info, for reference in case its useful:

```
ubi-standard-minimal.ubi9                         latest         df45ef08e130   1 second ago    96MB
ubi-standard.ubi9                                 latest         496eed5cb7bb   7 seconds ago   212MB
ubi-standard-minimal.ubi8                         latest         84005021ec49   19 months ago   103MB
ubi-standard.ubi8                                 latest         bcffdd54b645   19 months ago   205MB
ubi-standard-minimal.ubi7                         latest         39f1980e3cc3   2 years ago     81.3MB
ubi-standard.ubi7                                 latest         fbd5e2ec217f   2 years ago     204MB

alpine                                            latest         9c6f07244728   2 months ago    5.54MB 
```

**Comment by tellison** [comment]
@smlambert any further testing implications for this?

**Comment by karianna** [comment]
Ah crud, pulled the trigger too soon on merging possibly - LMK if you want me to reverse that PR

**Comment by gdams** [comment]
We don't have to publish the UBI images to the eclipse-temurin registry yet so no harm done, I'd like to hear from @smlambert before we push the images though

**Comment by sxa** [comment]
To be clear, will this require any extra action when we push up the remaining ones for the current release cycle (we're not complete on s390x yet AFAIK), or will UBI9 not be included in those even though the PR has been merged?

**Comment by smlambert** [comment]
I think for all of our containers to date we have two aspects to testing:
1. the testing done by the Docker team regarding the container itself (referenced in other issues, for example referenced in: [containers/267](https://github.com/adoptium/containers/issues/267)) 
1. the external container-based testing we do, where we can choose to pull any image we publish and run application tests on them.  This testing is currently constrained at the moment, not being done on all platforms that we have produced containers for, and not for all tags, mainly due to limited machine resources, [tool.sw.docker](https://ci.adoptopenjdk.net/label/sw.tool.docker/) labeled machines.

For 1) I presume that is all in place, with UBI images moving towards official status.  For 2) I think it would be good for us to kick off some Grinders to see how these images behave, but we would still not have a plan to enable on a regular basis (related: https://github.com/adoptium/ci-jenkins-pipelines/issues/219 and https://github.com/adoptium/ci-jenkins-pipelines/issues/273).

**Comment by tellison** [comment]
See also _eclipse-temurin: add UBI minimal support_ https://github.com/docker-library/official-images/pull/13533

**Comment by jiekang** [comment]
I see ubi-9-minimal images on this search: https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=ubi

Is there further work planned for this issue?

**Comment by gdams** [comment]
Let's close this now. There is a separate aqa-tests issue to track progress there

**Comment by jiekang** [comment]
> Let's close this now. There is a separate aqa-tests issue to track progress there

https://github.com/adoptium/aqa-tests/issues/4152
