### ISSUE TITLE
Deprecate 1809 image tag in favor of ltsc2019

### ISSUE THREAD

**Issue by sbaeurle** [adoptium/containers#329]
### What feature do you want to see added?

Windows discontinued the semi-annual release channel for their container base images (both nanoserver and servercore).
Instead they switched to LTSC releases and adjusted their naming scheme accordingly. (see https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison and https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle).

This repo uses a mix of this naming scheme with `1809` for the Server 2019 Image and `ltsc2022` for the 2022 one.
Would it be possible to streamline the tagging schema to push the `ltsc2019` tag either in favor of `1809` or concurrently to it?

**Comment by karianna** [comment]
Taking to the PMC when we all get back from holidays.

**Comment by sbaeurle** [comment]
@karianna quick follow up: did you have the chance to discuss this internally?

**Comment by karianna** [comment]
Added the right label for this to be picked up!

**Comment by tellison** [comment]
The PMC discussed this issue in today's meeting.

There was no desire to deprecate the original tag since we believe that it is still in popular usage. It was noted that the 1809 release is shown as being available in mainstream support until 01/09/2024, a further ~1.5yrs.

The demand for the new tag is deemed low, as it is well known as the original 1809 name at this point, therefore we propose not to add a further tag. The wide range of image tags [can be seen here](https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#supported-tags-and-respective-dockerfile-links).
